export const GET_ALL_ROOM = 'GET_ALL_ROOM';
export const GET_ALL_ROOM_SUCCESS = 'GET_ALL_ROOM_SUCCESS';
export const GET_ALL_ROOM_FAILED = 'GET_ALL_ROOM_FAILED';

export const GET_CATE_BY_ROOM = 'GET_CATE_BY_ROOM';
export const GET_CATE_BY_ROOM_SUCCESS = 'GET_CATE_BY_ROOM_SUCCESS';
export const GET_CATE_BY_ROOM_FAILED = 'GET_CATE_BY_ROOM_FAILED';
