export const GET_USER_WISHLIST = 'GET_USER_WISHLIST';
export const GET_USER_WISHLIST_SUCCESS = 'GET_USER_WISHLIST_SUCCESS';
export const GET_USER_WISHLIST_FAILED = 'GET_USER_WISHLIST_FAILED';

export const UPDATE_USER_WISHLIST = 'UPDATE_USER_WISHLIST';
export const UPDATE_USER_WISHLIST_SUCCESS = 'UPDATE_USER_WISHLIST_SUCCESS';
export const UPDATE_USER_WISHLIST_FAILED = 'UPDATE_USER_WISHLIST_FAILED';
