export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAILED = 'GET_ALL_CATEGORY_FAILED';

export const GET_CATE_BY_ROOM = 'GET_CATE_BY_ROOM';
export const GET_CATE_BY_ROOM_SUCCESS = 'GET_CATE_BY_ROOM_SUCCESS';
export const GET_CATE_BY_ROOM_FAILED = 'GET_CATE_BY_ROOM_FAILED';
