export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS';
export const GET_ALL_PRODUCT_FAILED = 'GET_ALL_PRODUCT_FAILED';

export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAILED = 'GET_PRODUCT_DETAIL_FAILED';

export const GET_PRODUCT_CATEGORY = 'GET_PRODUCT_CATEGORY';
export const GET_PRODUCT_CATEGORY_SUCCESS = 'GET_PRODUCT_CATEGORY_SUCCESS';
export const GET_PRODUCT_CATEGORY_FAILED = 'GET_PRODUCT_CATEGORY_FAILED';

export const GET_PRODUCT_ROOM = 'GET_PRODUCT_ROOM';
export const GET_PRODUCT_ROOM_SUCCESS = 'GET_PRODUCT_ROOM_SUCCESS';
export const GET_PRODUCT_ROOM_FAILED = 'GET_PRODUCT_ROOM_FAILED';
